[project]
name = "mcp-all-dockerized"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "httpx>=0.28.1",
    "openai>=1.96.0",
    "openai-agents>=0.2.0",
    "secedgar>=0.6.0",
]
